language: python
notifications:
  email: false
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - echo "no scripts"
after_success:
  - bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
